### ISSUE TITLE
Display zeigt "NO KODI ACCESS!"

### ISSUE THREAD

**Issue by dsiggi** [bjoern-reichert/KodiDisplayInfo#2]
Hallo,
ich möchte gern dein kleines Programm nutzen aber leider schein es keine Verbindung zu kodi aufzubauen.

In der config habe ich folgendes eingestellt:

```
[KODI_WEBSERVER]
# Set it to localhost or IP (192.168.2.101)
HOST = localhost
# Port of the Kodi Webserver
PORT = 8080
# Username
USER = kodi
# Password
PASS = kodi
```

Der Webserver läuft definitiv, über Chrome habe ich Zugriff darauf und auch mit diversen Bash-Scripten greife ich darauf zu.

Trotzdem wir im Display "NO KODI ACCESS!" angezeigt.

Wäre super wenn du mir hier helfen könntest.

**Comment by dsiggi** [comment]
Ich habs mit ein paar Änderungen in 'KODI_WEBSERVER.py' zum laufen gebracht.
Anscheinend kommt urllib2 nicht mit der Angabe von Benutzer:Passwort in der URL zurecht.
Im Anhang ist ein patch mit dem es nun bei mir funktioniert.

[KODI_WEBSERVER.txt](https://github.com/bjoern-reichert/KodiDisplayInfo/files/687026/KODI_WEBSERVER.txt)

**Comment by dsiggi** [comment]
Hier noch mal der patch, da ist wohl was mit den Zeilenumbrüchen falsch gelaufen.
[KODI_WEBSERVER.txt](https://github.com/bjoern-reichert/KodiDisplayInfo/files/687031/KODI_WEBSERVER.txt)

**Comment by bjoern-reichert** [comment]
Changed! THX.
